# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_auto_20170116_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
