# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 22:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0005_auto_20170117_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviewers',
            field=models.ManyToManyField(related_name='reviewed_products', through='commerce.Review', to=settings.AUTH_USER_MODEL),
        ),
    ]
